GET https://www.nalog.gov.ru/

###

GET https://jsonplaceholder.typicode.com/todos/

###

POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "name": "Vika",
    "text": "Hello!"
}